env:
  global:
  - GCP_PROJECT_ID=pgr301-exam
  - tf_version=0.13.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: rh9ZWt8B5pddce+dSrBBHMCn/JIPtoVa5DqkTi/rKlX9YMCIIX3Mo/RflyWhwscWODmPH3qml5WEErWiFZnXSM4aMrkno2Fc4wJtDESn4hGiPvwRC7lTl8QYgnSfSBsC0nuN3YzqBvtlBHi+Xje0rNuIluZ7XBkHG8k1aEBU109Fex9g/uSfeeAj2fIkWssfPzyIRiDdh81yYSyXQuoPo1O9JF/ONmvbReUY/SU4Xf6rGiu9uaUdwf/WG0u9jHtvSiIid8MCyksCkhKruxxMPPYxkyHNsIEIdizHEfwcCCakYbIdyWVKHN6JMgleObqGI+sgAukOiDJyXzDciSSEdqDsVvQVD8Z3nkcnh9nReWK8GX4hufWMpKnyyH7PMXqoX/36sodBjssctMdG32TUQDVXdK/UWjhzY6H+y33lU8vE3jiOhyMuubUUPduxgCmXRCf7CXiJutiNt5lWU86I08tdyzDCmizgty/knz4IJ5DpBHUiUk4GnH85Me/J23EYppFD9XOyggTxDVeVQbhN8L3ig3UMw/EUIMlpOuEJd4LPETW27XbOFak/4CGNyuAMD6Mm+kFGiYC2TcJvvnl5X7o+qz3r5QzxgBpyjA/wLU8+IAC/VwpPZYi9ske9R7gTCDrECDJNZ/REAbWDfTU9OPr2ZYfpR9X/UXXL2vl15G0=
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_0e22ff5f343b_key -iv $encrypted_0e22ff5f343b_iv
  -in pgr301-exam-ad93aab2bdd9.json.enc -out pgr301-exam-ad93aab2bdd9.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=pgr301-exam-ad93aab2bdd9.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./pgr301-exam-ad93aab2bdd9.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
