env:
  global:
    - GCP_PROJECT_ID=pgr301-exam
    - tf_version=0.12.19
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
branches:
  only:
    - main
before_install:
  - openssl aes-256-cbc -K $encrypted_0e22ff5f343b_key -iv $encrypted_0e22ff5f343b_iv -in pgr301-exam-ad93aab2bdd9.json.enc -out pgr301-exam-ad93aab2bdd9.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=pgr301-exam-b0bef1aea48c.json
  - gcloud config set project "${GCP_PROJECT_ID}"
  - export GOOGLE_APPLICATION_CREDENTIALS=./pgr301-exam-b0bef1aea48c.json
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
  - |-
    set -ex;
    terraform init
    terraform plan
    terraform apply --auto-approve
    terraform output