env:
  global:
  - GCP_PROJECT_ID=pgr301-exam
  - tf_version=0.13.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: utunFVU+Ul1QI1QZEov1jPDX7N8vAEPkt1qEVIaVVcGshDvxdyuP5o09ExFUXQ5kXJ9J4xutpG63Qgw5gYsQmfzAnYi1f/DYZ/w1fDQQ2VTmPOoeGIXFUx0tsgYGZ/hlFb4p3WNRuurD1N3KqvGQOBhpqoht+zktSSa/fUbyTIAh2lwIbJtuoBwtAaTDnU8UzzP3bYm1FhhQDom4zwDXaaUO1L/Bw2iwIQV7OdTUdjyf+rWk1UJrnXvO83crQ0CGHX2IdWo6YUDqnNG8RRDnVe/AFz7DUXDWslJ86mlwbf1j5KTeJVnme+BGhHyrw2JV1uBfhtLSwfpSopGULwjLgNj8tUIh0XXc3IoNJrngI/PorfxRH3cgyeWE63U0ov5HiwTCxgLEooc5cbYwwQYR8k3McbAHiWgWs6lGoEtbCczA5bk8siihJDh7O8QLnoooV+gR27/xxjFazjSo54PzzHlgpEKc9TwaQLOa0UsjS5+wKAxXeYMpdA4+sVbqbJ9xNELJlJF1i1ImRmHrxp3z9XQdgcLO3oX6E+SMImRXH7ycrfPNqum0g4wQIEs7U8tXEU6m/PnFW/rdMXaWCCRpAIbFYmBKrLmGuehqMb4mxMRFoNfW6RDpDxyxeKluBwluU1Kojnx9ufAPwCwr0/l6o9SYS7VqSqhVpwXrNR/+5AE=
  - secure: NOEws1UTk+nP6mIYSMVGjz4sEmIhwndtstuUZi71p1FeIgV9qG1f3gsd60AJAFmF4lHmxQ84be7Wk425s3cGM8PGrBPPH3TrN0LDmWxCwn1YbjaObgczrVDWZXOJ05sevsx69vd7d+ggjt/XAvIXd173yS/WhRV9Atl+gRUOTyBgBfrXOkumU+ZHkWKyqJlRf4hFbTwv/R/vTuQyBigIO/0CxwO5ccWbb+VkLZBzrfH/d2smp6rBczyRPNh62uT/kHELQ4yz8V4XcKQr4+AHvBRBKE1VP9pY3tfsQLjZcmwvGOymNBrSTDdXoWhElXEwW40QBYnLxPyJg+OfEv4W9p0C6+bERx2H2JNt0wbY4WniboVhtdtLy1f4zCCpdX1gYDjsmGvFRPM2ZmTZ4ohCBPtoTYXWoUGSjhrLznMlZ50vuWY/V32iyRtbyBBxKosqYqJLlJVQzpLfrW2mfi1NAvNDHv16u6qtCH6P0wj4xQQZ/v6btgiKJlp2uAQvNS7dgRPmpP7fQDrqmr/yzG2jFA0v0XalZa3uTBXJJmS0tjswVlTBiuX4TlR4BNTGT1bvhI5LgQucQB81zulZ4uBJQJIvv+Fd4/Jdk3ANHNs87v2kS+qmyoaRZNMpDYPjA7KZQT237eARs705gsMEtF4Ozt3Tf9ssVhbazB7cJA/aeTA=
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_0e22ff5f343b_key -iv $encrypted_0e22ff5f343b_iv
  -in pgr301-exam-ad93aab2bdd9.json.enc -out pgr301-exam-ad93aab2bdd9.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=pgr301-exam-ad93aab2bdd9.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./pgr301-exam-ad93aab2bdd9.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;

  export STATUSCAKE_KEY=$(gcloud secrets versions access latest --secret=STATUSCAKE_APIKEY)

  export TF_VAR_logz_token=$LOGZ_TOKEN
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
